### ISSUE TITLE
StreamReader issues trim command before xadd in replication log

### ISSUE THREAD

**Issue by kamran-redis** [RedisGears/RedisGears#1000]
When setting isStreamTrimmed: true for a streamtrigger trim command is sent before xadd command to replication log and entry is not removed in the replica

Version:  redis/redis-stack:7.2.0-RC3

## Reproduce:
use the following gear lib
```js
#!js api_version=1.0 name=chain1

const stream1 = 's1'

function stringfyEvent(event) {
    return JSON.stringify(event, (key, value) =>
        typeof value === 'bigint'
            ? value.toString()
            : value
    )
}

function createStreamEntryProcesser(name) {
    f = (client, event) => {
        redis.log(name + ':' + destination + ': ' + stringfyEvent(event))
    }
    return f
}

redis.registerStreamTrigger(stream1, stream1, createStreamEntryProcesser(stream1), { description: 'process a stream entry ' + stream1, isStreamTrimmed: true, window: 1 })
```

Attach a replicaof  `redis-cli --replica`  and when you add an entry `xadd s1 * a b c d`  you will see the follwoing replication commands. NOTICE xtrim is sent before xadd and entry will be in the replica
```
"MULTI"
"SELECT","0"
"_rg_internals.update_stream_last_read_id","chain1","s1","s1","1690214825176","0"
"xtrim","s1","MINID","1690214825176-1"
"xadd","s1","1690214825176-0","a","b","c","d"
"EXEC"
```

**Comment by MeirShpilraien** [comment]
Thanks for reporting @kamran-redis.
This should fix it: https://github.com/RedisGears/RedisGears/pull/1001
