### ISSUE TITLE
Calling KeyspaceTrigger and StreamTrigger  Creates a loop 

### ISSUE THREAD

**Issue by kamran-redis** [RedisGears/RedisGears#1005]
Running the library below creates an infinite loop. Either this is a bug or document is not clear.

# How to reproduce
version:  redis/redis-stack:7.2.0-RC3

Upload the script `redis-cli -x TFUNCTION LOAD REPLACE < bug2.txt` and run `redis-cli set foo bar` and you will see the following output in a loop. You can also create by the following command `redis-cli xadd s1 "*"  a b`
```
9:M 26 Jul 2023 11:30:09.702 * <redisgears_2> 'redisgears::compiled_library_api' keyspace: {"event":"set","key":"foo","key_raw":{}}
9:M 26 Jul 2023 11:30:09.703 * <redisgears_2> 'redisgears::compiled_library_api' s2: {"id":["1690371009700","0"],"stream_name":"s2","stream_name_raw":{},"record":[["name","keyspace"]],"record_raw":[[{},{}]]}
9:M 26 Jul 2023 11:30:09.703 * <redisgears_2> 'redisgears::compiled_library_api' keyspace: {"event":"xadd","key":"s2","key_raw":{}}
9:M 26 Jul 2023 11:30:09.703 * <redisgears_2> 'redisgears::compiled_library_api' s2: {"id":["1690371009700","1"],"stream_name":"s2","stream_name_raw":{},"record":[["name","keyspace"]],"record_raw":[[{},{}]]}
9:M 26 Jul 2023 11:30:09.703 * <redisgears_2> 'redisgears::compiled_library_api' keyspace: {"event":"xadd","key":"s2","key_raw":{}}
9:M 26 Jul 2023 11:30:09.703 * <redisgears_2> 'redisgears::compiled_library_api' s2: {"id":["1690371009700","2"],"stream_name":"s2","stream_name_raw":{},"record":[["name","keyspace"]],"record_raw":[[{},{}]]}
```
[bug2.txt](https://github.com/RedisGears/RedisGears/files/12171901/bug2.txt)

**Comment by MeirShpilraien** [comment]
Good catch, its a bug, we do not support key space notifications when triggered from within a gear.

**Comment by MeirShpilraien** [comment]
Actually this is not a bug, inside the stream processing callback you are adding more elements to the stream. So this makes sense that it will run forever. The hard part is to detect it and given indication that something is probably wrong and also allow to stop it, its another stop that we are currently working on...

**Comment by kamran-redis** [comment]
Hi Meir Not correct. When you `set foo bar`. The keyspace function writes to stream s2 but the triggered stream function does not as the value of second stream is null and processing should terminate.

I added both examples to show this infinite loop can happen both from keyspace and stream

**Comment by MeirShpilraien** [comment]
Taking it back, you are right, its a bug in our notification blocker. Will submit a fix soon.
