### ISSUE TITLE
JavaScript API special characters in trigger names

### ISSUE THREAD

**Issue by vzambo64** [RedisGears/RedisGears#1088]
The API allows only characters plus '_' in the trigger names of JavaScript API.
The verify_name function checks the trigger names in the
-   register_stream_consumer
-   register_key_space_notification_consumer
functions.

However, the Redis module events contain special characters, for example: "ts.add:dest" trigger name emitted by the time-series module.
Different error checks are required for trigger names allowing special characters that Redis and modules are using like this:

pub(crate) fn verify_trigger_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("Empty name is not allowed".to_owned());
    }
    name.chars().try_for_each(|c| {
        if c.is_ascii_alphanumeric() || "_.:".find(c).is_some()  {
            return Ok(());
        }
        Err(format!("Unallowed char was given '{c}'"))
    })
}

There is no limitation on characters used in Redis trigger names so the whole check might be removed...

versions tested:
redis 7.2.2
redisgears (master: cb9d4d3d58064768bc66a37f7e7fb1af16480207)

**Comment by MeirShpilraien** [comment]
I am not sure I follow what is your concern. The trigger name or the stream consumer name has nothing to do with the triggers that you can receive from Redis, its just a name that is used to replace the trigger logic when you update your library.

**Comment by vzambo64** [comment]
I was trying to register a JS function on the time-series "ts.add:dest" event.
`TFUNCTION LOAD REPLACE "#!js name=library api_version=1.0\n function publishMessage(client, data) { if(data.event === 'ts.add:dest') { client.call('publish', 'js-publish',Date.now().toString()); } } redis.registerKeySpaceTrigger('ts.add:dest', '*', publishMessage);"
`
The redis.registerKeysSpaceTrigger drops error, because the "ts.add:dest" string contains "." and ":" characters, and allows only alphanumeric characters and "_" characters validated with the "verify_name" function.
The notification triggers in Redis are not limited so strict in the pub/sub triggers names - any character can be used, but some need to be escaped.
For that purpose suggested to use different validator function for names and pub/sub trigger names.

**Comment by MeirShpilraien** [comment]
As I wrote above and as the [documentation](https://github.com/RedisGears/RedisGears/blob/master/docs/docs/concepts/triggers/KeySpace_Triggers.md) says, the first argument to `registerKeySpaceTrigger` is the consumer name, its just a name you chose for your consumer so we will know to replace it on updates. It has nothing to do with the notification that Redis or any module fires, you will get all the notifications to your callback and you need to filter them on the callback itself.

**Comment by vzambo64** [comment]
Thank - you, got it! It is clear now.
