### ISSUE TITLE
Atomic execution on shard level

### ISSUE THREAD

**Issue by K-Jo** [RedisGears/RedisGears#152]
Certain executions might require to be done in an atomic way. e.g. if you want to update all keys that meet a certain <condition>.  RedisGears should optionally allow to execute these atomically, at least on shard level.

**Comment by MeirShpilraien** [comment]
Master contains the ability to register SYNC execution that runs on the main thread. We can expose this capability to executions as well (.run() and not only .register()). One disadvantage is that SYNC executions are local to the shard and not distributed.
