### ISSUE TITLE
make all error - Cannot find redis-server.

### ISSUE THREAD

**Issue by AlexTereshenkov** [RedisGears/RedisGears#158]
I am attempting to build `RedisGears` on Ubuntu 18.04 by running the following commands:

```
make setup
make fetch 
make all
```

When running `make all`, the process stops with the error:

```
...
Compiling src/module_init.c...
Compiling src/redisgears_python.c...
Linking bin/linux-x64-release/redisgears.so...
Cannot find redis-server. Aborting.
Makefile:220: recipe for target 'pack' failed
make: *** [pack] Error 1
```

I wasn't able to find any guidelines on how to build the `RedisGears`, but I guess I may be missing a few dependencies. Does anyone know what are the build requirements? @gkorland

**Comment by MeirShpilraien** [comment]
@AlexTereshenkov seems like you do not have redis server install...

**Comment by AlexTereshenkov** [comment]
> @AlexTereshenkov seems like you do not have redis server install...

I suspected this. Do you know what exactly should be installed? Is it just `sudo apt install redis-server`?

**Comment by MeirShpilraien** [comment]
It is best to just build from source : https://github.com/antirez/redis
Just checkout version 5.0.6:
git checkout 5.0.6
make
sudo make install
