### ISSUE TITLE
Make setup: permission denied

### ISSUE THREAD

**Issue by irthomasthomas** [RedisGears/RedisGears#178]
Hi, 
I'm trying to install on a new system (ubuntu 18.04) and having trouble. Running make setup without sudo gives the error below. I've tried the main branch and 0.4 and they both fail. If I run sudo make setup, that works, but then the next steps fail.

make setup
Setting up system...
apt-get -qq update -y
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
command failed: apt-get -qq update -y
Makefile:184: recipe for target 'setup' failed
make: *** [setup] Error 1
tommy@t440:~/redisgears$ 

Cheers
Tommy

**Comment by MeirShpilraien** [comment]
@rafie should it work now?
