### ISSUE TITLE
Redis crashing after running script from example

### ISSUE THREAD

**Issue by AkshayAnurag** [RedisGears/RedisGears#214]
Hi,
I was running the example from `RedisMultiModel` repository (https://github.com/RedisGears/MultiModelExample/blob/master/script.sh)

Redis is crashing in all these setups:
(Ubuntu 18.04)
RedisGears version: **0.4.0 preview release**

1. Redis Latest Stable version (5.0.7) [built from source] + modules loaded from `so` files
2. Redis version (4.0.9) [install from `aptitude package manager`] + modules loaded from `so` files
3. Redis pulled from latest docker (redismod): `docker run -p 6379:6379 redislabs/redismod
`

After adding the register:
`RG.PYEXECUTE "GearsBuilder().foreach(lambda x: execute('FT.ADDHASH', 'marsmen', x['key'], '1.0', 'REPLACE')).register('marsman:*')"`

If I add a new hash (`HSET marsman:101 Name Lori Last Quaid`), then Redis crashes.

_It happens regardless if I execute from the script or directly from `redis-cli`._

All commands before it execute without any error.

**Error/Info:**
[Error_Info.pdf](https://github.com/RedisGears/RedisGears/files/4214307/2osbr-justpasteit.pdf)

**Comment by AkshayAnurag** [comment]
Let me know if you need more information.

**Comment by MeirShpilraien** [comment]
Please specify the redisearch version you are using and notice that gears only works with redis 5.0.7 and above.

**Comment by AkshayAnurag** [comment]
@MeirShpilraien Thanks for the quick response.

RedisGears version: **0.4.0 preview release**

I have tried with Redis 5.0.7 as well.

**Comment by MeirShpilraien** [comment]
Did you compiled RedisGears yourself? Can you test with current master?

**Comment by AkshayAnurag** [comment]
Yes, I had tried both ways:

1. Compiled from source code of the master branch
2. Ran from docker

I got the same error in both cases.

**Comment by MeirShpilraien** [comment]
Just run it locally and its not crashing:
```
127.0.0.1:6379> RG.PYEXECUTE "GearsBuilder().foreach(lambda x: execute('FT.ADDHASH', 'marsmen', x['key'], '1.0', 'REPLACE')).register('marsman:*')"
OK
127.0.0.1:6379> HSET marsman:101 Name Lori Last Quaid
(integer) 2
127.0.0.1:6379> RG.DUMPREGISTRATIONS
1)  1) "id"
    2) "0000000000000000000000000000000000000000-0"
    3) "reader"
    4) "KeysReader"
    5) "desc"
    6) (nil)
    7) "RegistrationData"
    8)  1) "mode"
        2) "async"
        3) "numTriggered"
        4) (integer) 1
        5) "numSuccess"
        6) (integer) 1
        7) "numFailures"
        8) (integer) 0
        9) "numAborted"
       10) (integer) 0
       11) "lastError"
       12) (nil)
       13) "args"
       14) 1) "regex"
           2) "marsman:*"
           3) "eventTypes"
           4) (nil)
           5) "keyTypes"
           6) (nil)
    9) "PD"
   10) "{'sessionId':'0000000000000000000000000000000000000000-0', 'depsList':[]}"
```
Can you share the output of the master (full log file including the crash report)?
Also which redisearch version are you using?

**Comment by AkshayAnurag** [comment]
Redisearch version: **Built from master (1.6.8)**

I tried again with:
Redis: 5.0.7
RedisGears: built from master (0.4.0 preview release)
Redisearch: built from master (1.6.8)
RedisGraph: built from master (2.0.1)
RedisTimeSeries: built from master (1.2.3)

This time I didn't get any issues until Redisearch commands but then upon registering redisgraph related commands, it crashed.
(https://github.com/RedisGears/MultiModelExample/blob/master/script.sh#L77)

`# Register for new nodes/relations update
redis-cli RG.PYEXECUTE \
"GearsBuilder()\
.foreach(lambda x: execute('GRAPH.QUERY', 'marsmen', 'MERGE ( :marsman {ID:\"%s\"})' % x['key']))\
.foreach(lambda x: execute('GRAPH.QUERY', 'marsmen', 'MATCH (n:marsman {ID:\"%s\"}) SET n.Name=\"%s\", n.Last=\"%s\"' % (x['key'], x['value']['Name'], x['value']['Last'])))\
.foreach(lambda x: execute('GRAPH.QUERY', 'marsmen', 'MATCH (a:marsman)-[r:Relation]->() where a.ID=\"%s\" DELETE r' % (x['key'])))\
.filter(lambda x: 'Relation' in x['value'].keys())\
.foreach(lambda x: execute('GRAPH.QUERY', 'marsmen', 'MATCH (a:marsman), (b:marsman) where a.ID=\"%s\" AND b.ID=\"%s\" CREATE (a)-[:Relation]->(b)' % (x['key'], x['value']['Relation'])))\
.register('marsman:*')"`

Log file: 
[redis-log.log](https://github.com/RedisGears/RedisGears/files/4217880/redis-log.log)

**Comment by MeirShpilraien** [comment]
This looks like a crash on RedisGraph which probably related to the fact that graph perform the query in background thread.
@swilly22 any way we can tell graph to perform the query in the current thread when using RM_Call? Also if you can take a look at the crash report, maybe you can spot something which tells us why it crashing?

**Comment by MeirShpilraien** [comment]
@AkshayAnurag I talked to @swilly22 internally and looks like I was right about my suspicious, we will update you when we have a solution that will allow redisgraph to know that it was called from inside a module and not to take the execution to another thread.

**Comment by MeirShpilraien** [comment]
If you want a workaround for now you can run a small lua that called the graph query and call this lua from the gear execute command. Graph will identify that it was called from within a lua and will not pass the execution to another thread.

**Comment by MeirShpilraien** [comment]
Closing (Graph issue, which I believe was already resolved.)
