### ISSUE TITLE
Add key type to readers' output

### ISSUE THREAD

**Issue by itamarhaber** [RedisGears/RedisGears#238]
It would be good to have an additional 'type' value (e.g. "string", "hash",...) to the records that are output by KeysReader. The same for KeysOnlyReader, but also support disabling that feature in that case (to reduce latency when type isn't needed, e.g. when the user puts a single type in the whitelist).

**Comment by MeirShpilraien** [comment]
Its not always available for register, for example if key was delete I only know it was deleted so its going to be best efforts ..

**Comment by MeirShpilraien** [comment]
Fixed
