### ISSUE TITLE
RG.PYEXECUTE fails on v0.9

### ISSUE THREAD

**Issue by irthomasthomas** [RedisGears/RedisGears#280]
I'm trying to upgrade my redis stack to the latest versions but my projects gear fails to register.
Working: Ubuntu18.04 / redis-5.0.7 / redisgears-0.4.0
Not working: Ubuntu18.04 / redis-5.0.8 / redisgears-0.9.0

redis-cli RG.PYEXECUTE "$(cat ~/scrape/tom/oldgear/gear.py)"
(error) ['Traceback (most recent call last):\n', '  File "<string>", line 230, in <module>\n', '  File "<string>", line 136, in register\n', 'spam.error: Error occured when serialized a python callback, callback=runModel2 error=[\'Traceback (most recent call last):\\n\', \'  File "<string>", line 954, in dumps\\n\', \'  File "<string>", line 267, in dump\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 437, in dump\\n    self.save(obj)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 504, in save\\n    f(self, obj) # Call unbound method with explicit self\\n\', \'  File "<string>", line 397, in save_function\\n\', \'  File "<string>", line 596, in save_function_tuple\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 504, in save\\n    f(self, obj) # Call unbound method with explicit self\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 856, in save_dict\\n    self._batch_setitems(obj.items())\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 882, in _batch_setitems\\n    save(v)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 504, in save\\n    f(self, obj) # Call unbound method with explicit self\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 856, in save_dict\\n    self._batch_setitems(obj.items())\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 882, in _batch_setitems\\n    save(v)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 549, in save\\n    self.save_reduce(obj=obj, *rv)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 662, in save_reduce\\n    save(state)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 504, in save\\n    f(self, obj) # Call unbound method with explicit self\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 856, in save_dict\\n    self._batch_setitems(obj.items())\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 882, in _batch_setitems\\n    save(v)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 549, in save\\n    self.save_reduce(obj=obj, *rv)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 662, in save_reduce\\n    save(state)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 504, in save\\n    f(self, obj) # Call unbound method with explicit self\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 856, in save_dict\\n    self._batch_setitems(obj.items())\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 882, in _batch_setitems\\n    save(v)\\n\', \'  File "/var/opt/redislabs/lib/modules/python3/lib/python3.7/pickle.py", line 524, in save\\n    rv = reduce(self.proto)\\n\', "TypeError: can\'t pickle _thread.lock objects\\n"]\n']

**Comment by MeirShpilraien** [comment]
Seems like your runModel2 function is not serializable, can you share gear.py code?

**Comment by irthomasthomas** [comment]
`from stop_words import get_stop_words
import re
import string
# from sklearn.feature_extraction.text import TfidfVectorizer
import pickle
import numpy as np
import time
from redis import Redis

conn = Redis()

vectorizer = pickle.load(open("vectorizer.pickle", "rb"))
stopwords = get_stop_words('english')

def pre_proc_text(x):

    def extract_hashtags(caption):
        regexp = re.compile(r"(?:#)(\w(?:(?:\w|(?:\.(?!\.))){0,28}(?:\w))?)")
        tags = []

        def repl(m):
            tag = m.group(0)[1:]
            tags.append(tag)
            return ""

        caption = regexp.sub(repl, caption.lower())
        return caption, tags

    def extract_mentions(caption):
        regexp = re.compile(r"(?:@)(\w(?:(?:\w|(?:\.(?!\.))){0,28}(?:\w))?)")
        tags = []

        def repl(m):
            tags.append(m.group(0))
            return ""

        caption = regexp.sub(repl, caption.lower())
        return caption

    def remove_punct(text):
        translator = str.maketrans('', '', string.punctuation)
        return text.translate(translator)

    def tokenize(text):
        # TODO: Anomalous backslash in string
        text = re.split('\W+', text)
        return text

    def remove_stopwords(text, stopword):
        text = [word for word in text if word not in stopword]
        return text
 
    caption = x['caption']

    caption, tags = extract_hashtags(caption)
    
    caption_text = extract_mentions(caption)
    caption = caption_text

    caption = remove_punct(caption)
    caption = tokenize(caption)
    caption = remove_stopwords(caption, stopwords)

    caption = ' '.join(caption)
    caption = caption.rstrip()

    return x, caption, caption_text, tags


def is_first_page(x):
    ''' If this is the first page
        add tags to queue:burst
        or else carry on through gear '''
    if x[0]['is_first_page'] == 'False':
        return x
    else:
        rootTag = x[0]['rootTag']
        t = 1
        for tag in x[3]:
            if tag == rootTag:
                continue
            key = f'root:tag:{tag}'
            execute('SET', key, rootTag)
            added = execute('SADD', 'queue:burst', tag)
            if added:
                execute('LPUSH', 'list:burst', tag)
            if t > 3:
                return x
            else:
                t += 1
        return x


def is_too_short(x):
    ''' If caption length is too small
        it's not worth predicting. '''
    if len(x[2]) > 15:
        return True
    else:
        return False

def runModel2(x):
    caption = x[1]
    sample = vectorizer.transform([caption]).toarray()
    ba = np.asarray(sample, dtype=np.float32)
    conn.execute_command(
        'AI.TENSORSET', 'auction:tensor', 'FLOAT',
        '1', '80', 'BLOB', ba.tobytes())
    conn.execute_command(
        'AI.MODELRUN', 'auction:model',
        'INPUTS', 'auction:tensor',
        'OUTPUTS', 'out_label', 'out_probs')
    out = conn.execute_command(
        'AI.TENSORGET', 'out_label', 'VALUES')
    return out[2][0]


def storeResults(x):
    ''' store to output stream '''
    # TODO: PIPELINE

    rootTag = x[0]['rootTag']
    postId = x[0]['postId']
    shortcode = x[0]['shortcode']
    streamKey = f'tags:out:{rootTag}'
    link = f'https://www.instagram.com/p/{shortcode}'

    execute('XADD', streamKey,
        'MAXLEN', '~', 2500, '*',
        'link', link, 'caption_text', x[2],
        'rootTag', rootTag,
        'related_tag', x[0]['related_tag'],
        'postId', postId,
        'imgUrl', x[0]['imgUrl'],
        'likes', x[0]['likes'],
        'comments_count', x[0]['comments'],
        'shortcode', x[0]['shortcode'])

    res = execute('zincrby', 'topz:products', 1, rootTag)
    if x[0]['relatedTag'] == 'False':
        for tag in x[3]:
            execute('SADD', f'post:tags:{postId}', tag)
            execute('SADD', f'tag:posts:{tag}', postId)
        # TODO:STORE INFO ON RELATED in case one is hot
        execute('topk.add', 'top10tags', rootTag)
        execute('topk.add', 'top100tags', rootTag)
        
        execute('cms.IncrBy', f'sketch:out:{rootTag}', postId, '1') 
    

gb = GearsBuilder('StreamReader')
gb.map(pre_proc_text)
gb.map(is_first_page)
gb.filter(is_too_short)
gb.filter(runModel2)
gb.foreach(storeResults)
gb.register('post:')`

**Comment by MeirShpilraien** [comment]
Seems like you open a redis connection and use it in the `runModel2` function. I understand why you do it cause RedisAI pass the execution to a background thread and so you can not use execute. On v0.9.0 we persist the execution in the rdb so when you restart the redis you will not lose them, this is also why we enforce all registrations to be serializable.

A way to solve it is to set the `conn` to `None` and inside the `runModel2` check if its None and initialize it if it is:
```
if not conn:
    conn = Redis()
```

Another option is to use the onRegistered callback : https://oss.redislabs.com/redisgears/0.9/functions.html#register
```
onRegistered : A function callback that's called on each shard upon function registration. It is a good place to initialize non-serializable objects such as network connections.
```

**Comment by irthomasthomas** [comment]
@MeirShpilraien Ahh yes, that did the trick. Cheers.

**Comment by MeirShpilraien** [comment]
@irthomasthomas can we close this issue?

**Comment by irthomasthomas** [comment]
Yes that's fine.  Cheers.
