### ISSUE TITLE
huge Docker image size

### ISSUE THREAD

**Issue by andrascz** [RedisGears/RedisGears#322]
The image built from `Dockerfile` is pretty huge compared to the used base image: redislab/redisgears:1.0.0 ~800Mb vs redisfab/redis:6.0.1-x64-buster ~140Mb

According to [dive](https://github.com/wagoodman/dive) there are a couple of hundreds of Mb-s wasted and the actual file content inside the image is ~400Mb. Also as I have seen all `__pycache__` files for the Python distribution are embedded into the image by default (~60Mb).

**Comment by MeirShpilraien** [comment]
@andrascz thanks for the feedback, I will take a look at what can optimize there.

**Comment by MeirShpilraien** [comment]
This PR should reduce docker image size ..
https://github.com/RedisGears/RedisGears/pull/332

**Comment by andrascz** [comment]
I have checked the edge image and it is now 421Mb. According to dive only 3.7Mb wasted space so I think this is a great development. Thank you for the effort.
