### ISSUE TITLE
Different Python minor versions on client/server side cause valueerror

### ISSUE THREAD

**Issue by chrisAtRedis** [RedisGears/RedisGears#384]
Exact error message is "ValueError: unsupported pickle protocol: 5\n"

Steps to reproduce:
1. Install redis and redisgears per github / redisgears.io instructions
2.Start redis with redisgears module loaded
3. The following Python script fails: 
```
>>> from gearsclient import GearsRemoteBuilder as GearsBuilder
>>> gb=GearsBuilder('KeysReader')
>>> gb.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/gearsclient/redisgears_builder.py", line 298, in run
    results = self.r.execute_command('RG.PYEXECUTE', serverCode, *self.requirements)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: ['Traceback (most recent call last):\n', '  File "<string>", line 3, in <module>\n', 'ValueError: unsupported pickle protocol: 5\n']
```
First observed when using Python 3.8 on the client side (the CPython version embedded in RedisGears seems to be 3.7.x). This can be reproduced across OSX 10.15.6 and Focal. 
Using the same version for both the client and server side works as expected (tested on an up-to-date Buster).

Let me know if you need more info.

**Comment by chrisAtRedis** [comment]
Cf. https://github.com/dask/dask/issues/6007. Seems to be known issue. Better add a caveat to the README.

**Comment by chrisAtRedis** [comment]
Or simply set the pickle.DEFAULT_PROTOCOL to 4 on the client side. For this particular example :-), not tested).

=== THIS IS A HACK ===
To be used by seasoned professionals only - do not try this at home kids!
=== THIS IS A HACK ===

**Comment by Gypsying** [comment]
> from gearsclient import GearsRemoteBuilder as GRB
> import redis
> conn = redis.Redis(host='x.x.x.x', port=6379, db=0, password='xxx')
> grb = GRB(reader='KeysReader', r=conn)
> grb.run()


python3.6 is ok while python3.8 occur error:
`redis.exceptions.ResponseError: ['Traceback (most recent call last):\n', '  File "<string>", line 3, in <module>\n', 'ValueError: unsupported pickle protocol: 5\n']`

**Comment by MeirShpilraien** [comment]
There is already an issue for this on RedisGears-Py repository
https://github.com/RedisGears/redisgears-py/issues/13
