### ISSUE TITLE
run Keyspace Notification Processing Demo and return deco() got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by KevinWu0904** [RedisGears/RedisGears#387]
I‘m newbee and try to setup RedisGears, because I want to trigger redis key expired event to redis stream. And I try to follow the official guide: https://oss.redislabs.com/redisgears/master/examples.html#keyspace-notification-processing

What I do is:
1. docker run -d --name redisgears -p 6379:6379 redislabs/redisgears:latest
2. cd ~ && vim test.py
3. paste 

```
def process(x):
    '''
    Processes a message from the local expiration stream
    Note: in this example we simply print to the log, but feel free to replace
    this logic with your own, e.g. an HTTP request to a REST API or a call to an
    external data store.
    '''
    log(f"Key '{x['value']['key']}' expired at {x['id'].split('-')[0]}")

# Capture an expiration event and adds it to the shard's local 'expired' stream
cap = GB('KeysReader')
cap.foreach(lambda x:
            execute('XADD', f'expired:{hashtag()}', '*', 'key', x['key']))
cap.register(prefix='*',
             mode='sync',
             eventTypes=['expired'],
             readValue=False)

# Consume new messages from expiration streams and process them somehow
proc = GB('StreamReader')
proc.foreach(process)
proc.register(prefix='expired:*',
              batch=100,
              duration=1)
```

4. cat test.py | docker exec -i redisgears redis-cli -x RG.PYEXECUTE

But I got the error in the terminal: deco() got an unexpected keyword argument 'prefix'

What am I missing ?

**Comment by MeirShpilraien** [comment]
Hey @KevinWu0904 
Can you share the redis log file?

**Comment by KevinWu0904** [comment]
@MeirShpilraien  Thanks for quick response.

Sure, 
![image](https://user-images.githubusercontent.com/37426896/89727422-46058c00-da57-11ea-813d-ab18a57b40a0.png)

wuguohua.5281@n227-008-193:~$ docker logs d0eef65b27a3
1:C 09 Aug 2020 05:05:11.157 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 09 Aug 2020 05:05:11.158 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 09 Aug 2020 05:05:11.158 # Configuration loaded
1:M 09 Aug 2020 05:05:11.159 * Running mode=standalone, port=6379.
1:M 09 Aug 2020 05:05:11.159 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 09 Aug 2020 05:05:11.159 # Server initialized
1:M 09 Aug 2020 05:05:11.159 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 09 Aug 2020 05:05:11.159 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 09 Aug 2020 05:05:11.161 * <rg> RedisGears version 0.3.1, git_sha=be5c5fcdf2abaabe5ff62155d9c38e0ecaa97575
1:M 09 Aug 2020 05:05:11.161 * <rg> PythonHomeDir:/opt/redislabs/lib/modules/python3
1:M 09 Aug 2020 05:05:11.161 * <rg> MaxExecutions:1000
1:M 09 Aug 2020 05:05:11.161 * <rg> ProfileExecutions:0
1:M 09 Aug 2020 05:05:11.161 * <rg> PythonAttemptTraceback:1
could not initialize RedisAI_GetAPIVersion
1:M 09 Aug 2020 05:05:11.161 # <rg> could not initialize RediAI api, running without AI support.
could not initialize RediSearch_CheckApiVersionCompatibility
1:M 09 Aug 2020 05:05:11.162 # <rg> could not initialize RediSearch api, running without Search support.
1:M 09 Aug 2020 05:05:11.176 * <rg> Initializing Python environment with: exec(open('/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py').read(), {'__file__': '/opt/redislabs/lib/modules/python3/.venv/bin/activate_this.py'})
1:M 09 Aug 2020 05:05:11.210 * Module 'rg' loaded from /opt/redislabs/lib/modules/redisgears.so
1:M 09 Aug 2020 05:05:11.210 * Ready to accept connections

**Comment by KevinWu0904** [comment]
Some other information:
![image](https://user-images.githubusercontent.com/37426896/89727509-2a4eb580-da58-11ea-8962-cbf8fa70fd45.png)

**Comment by MeirShpilraien** [comment]
You are running a very old version (0.3.1). Which is not even GA. Please make sure to pull the latest tag again and it should work.

**Comment by KevinWu0904** [comment]
@MeirShpilraien So what's the latest version number ?

**Comment by MeirShpilraien** [comment]
1.0.1

**Comment by KevinWu0904** [comment]
@MeirShpilraien Thank you very much, I will try this version tag again

**Comment by KevinWu0904** [comment]
After I trying the 1.0.1 version, it works. Thanks again
