### ISSUE TITLE
Question about execute

### ISSUE THREAD

**Issue by mrpre** [RedisGears/RedisGears#396]
The python script is run under an extra thread not under the `Redis` worker,  which means that the `execute()` also run under the thread.  Does there exist concurrency problems ? `Redis` is a single-threaded server, but in RedisGears an extra thread is used to write DB.

**Comment by MeirShpilraien** [comment]
@mrpre the execute function make sure to take the Redis GIL before executing the command, so you are safe.

**Comment by MeirShpilraien** [comment]
But you do need to consider that it's not atomic (if you perform execute twice), if atomicity is needed use `with atimic` (https://oss.redislabs.com/redisgears/runtime.html#atomic)

**Comment by mrpre** [comment]
I see...`RedisModule_ThreadSafeContextLock` is uesed.
