### ISSUE TITLE
gears_cli: import-requirements is broken

### ISSUE THREAD

**Issue by MikeClapper** [RedisGears/RedisGears#398]
This example command will demonstrate the problem:
python3 __main__.py import-requirements --requirements-path exports/redisgears-requirement-v1-pandas-linux-buster-x64.zip --host localhost --port 6399
This last lines of the output:
  File "/Users/mikeclapper/.pyenv/versions/3.7.5/lib/python3.7/zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "/Users/mikeclapper/.pyenv/versions/3.7.5/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

The problem appears to be in the routine 'import_requirements' - line 254 - 'import_single_req()' is called using a buffer rather than a file name.

253        io_buffer = io.BytesIO(req_data)
 245       import_single_req(r, io_buffer, bulk_size_in_bytes)

**Comment by MeirShpilraien** [comment]
@MikeClapper Can you open it on the gears-cli repository?

**Comment by MikeClapper** [comment]
This was submitted to the wrong project... I will close it now.
