### ISSUE TITLE
RG.CONFIGSET Not propagated to all shards

### ISSUE THREAD

**Issue by southwest-git** [RedisGears/RedisGears#405]
My understanding is once I used RG.CONFIGSET to set a runtime config e.g. ExecutionMaxIdleTime, every shard in the cluster will have this config updated. However, this doesn't seem to be the case

from rediscluster import RedisCluster
startup_nodes = [{"host": "127.0.0.1", "port": "6001"}]
rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=False)
rc.execute_command("RG.CONFIGSET", "ExecutionMaxIdleTime", 800000)
rc.execute_command("RG.PYEXECUTE", "GB('PythonReader').map(lambda x:execute('RG.CONFIGGET', 'ExecutionMaxIdleTime')).run(lambda :(i for i in range(1)))")

The output suggests only one shard is updated

[[b'[5000]',
  b'[5000]',
  b'[5000]',
  b'[5000]',
  b'[5000]',
  b'[800000]',
  b'[5000]',
  b'[5000]'],
 []]

My actual use case is GB().flatmap(foo1).repartition(foo2).run('data:*')

Data is in one shard only, foo1() took 10 secs to complete, by the time repartitioning occurred, all other shard were timed out.

This hack seems to do the job.

rc.execute_command("RG.PYEXECUTE", "GB('PythonReader').foreach(lambda x:execute('RG.CONFIGSET', 'ExecutionMaxIdleTime', 800000)).run(lambda :(i for i in range(1)))")

Is a bug or feature?

Thanks!

**Comment by MeirShpilraien** [comment]
This is not a bug, RG.CONFIGSET are a shard independent command, you can use gears to create the cluster version of it:
```
127.0.0.1:20000> RG.PYEXECUTE "GB('CommandReader').map(lambda r: execute('RG.CONFIGSET', r[1], r[2])).register(trigger='CLUSTER_CONFIG_SET')"
OK
127.0.0.1:20000> RG.TRIGGER CLUSTER_CONFIG_SET ExecutionMaxIdleTime 800000
1) "['OK']"
2) "['OK']"
3) "['OK']"
```
