### ISSUE TITLE
gitter chat link in doc just leads to an image

### ISSUE THREAD

**Issue by simonprickett** [RedisGears/RedisGears#435]
The gitter link in the Contact section here https://oss.redislabs.com/redisgears/ just links to an image.  Should like to gitter?

**Comment by K-Jo** [comment]
@gkorland probably discourt?

**Comment by gkorland** [comment]
@simonprickett try to refresh the page, it was updated a week ago

**Comment by simonprickett** [comment]
@gkorland still see same issue with empty cache and hard refresh on two machines... html:

```html
<li>
         <a href="https://badges.gitter.im/RedisLabs/RedisGears.svg">
          Gitter chatroom
         </a>
</li>
```

**Comment by gkorland** [comment]
![image](https://user-images.githubusercontent.com/753206/98604434-55ad9e80-22ec-11eb-87ee-e29beda0bce2.png)

**Comment by simonprickett** [comment]
@gkorland it's the one in the contact us section that I am reporting.
