### ISSUE TITLE
[FR] Remove a `register()`ed gear

### ISSUE THREAD

**Issue by itamarhaber** [RedisGears/RedisGears#44]

**Comment by sgama** [comment]
At this time, is it not possible to remove a "registered" gear?

In one of the examples, we are able to prevent any new keys from being entered into Redis:
```
RG.PYEXECUTE "GearsBuilder().foreach(lambda x: execute('del', x['key'])).register()"
```

Can we "undo" this registered gear? I tried something like:
```
RG.PYEXECUTE "GearsBuilder().foreach(lambda x: execute('add', x['key'])).register()"
```
Unfortunately it did not let me add new keys again. The only solution was to delete all container data and restart redis.

This issue is over a month old. I'm curious to know if it has been resolved yet.

**Comment by itamarhaber** [comment]
I'm quite positive it will be resolved soon - hang tight ;)

**Comment by MeirShpilraien** [comment]
@sgama re-add the key will not help because it will trigger another delete. We will soon support dropping register gear.

**Comment by MeirShpilraien** [comment]
Unregister is now supported.

**Comment by nishantgeorge** [comment]
Is it possible to unregister all registered functions with one command? Something like `FLUSHALL`?

**Comment by MeirShpilraien** [comment]
@nishantgeorge currently not but its a good feature request. Till then try to use this simple UI that allows you to unregister quickly https://github.com/RedisGears/RedisGearsMonitor.

**Comment by nishantgeorge** [comment]
Thank you @MeirShpilraien. Should I create another issue to track that feature request?

**Comment by MeirShpilraien** [comment]
@nishantgeorge yes, thank you.

**Comment by nishantgeorge** [comment]
Tracking that feature request in this issue: https://github.com/RedisGears/RedisGears/issues/285

Also, is there any way at all to clear the execution history (what is returned from [`RG.DUMPEXECUTIONS`](https://oss.redislabs.com/redisgears/commands.html#rgdumpexecutions)? The use case is that we are creating a UI for RedisGears and we need to clear the execution history as part of the teardown for our unit tests.

**Comment by nishantgeorge** [comment]
I see there's [`RG.DROPEXECUTION`](https://oss.redislabs.com/redisgears/commands.html#rgdumpexecutions). That should do the trick for now. Maybe also consider something for removing all executions in one command as well?
