### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by Rambatino** [RedisGears/RedisGears#464]
Hello, 

I'm getting compiler issues on:

```
➜  RedisGears git:(master) uname -a
Darwin Mark-Ramotowskis-16-MBP-2019 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```

After running all the commands, certain symbols can't be found in the flat namespace of redisgears.so:

```
➜  RedisGears git:(master) ✗ nm -C /Users/mark/zappi/RedisGears/bin/macos-x64-release/redisgears.so | grep libi
                 U _libiconv
                 U _libiconv_open
                 U _libiconv_set_relocation_prefix
0000000000034de0 T _libintl_bind_textdomain_codeset
0000000000034a60 T _libintl_bindtextdomain
0000000000034e10 T _libintl_dcgettext
````

e.g. _libiconv.

Most likely it's using `/usr/lib/libiconv.2.dylib` instead of `/usr/local/opt/libiconv/lib/libiconv.2.dylib` (which otool -l  confirms).  I tried changing it in the binary but I think because it's in the flat namespace it's not going to look in the lib and will just assume that it's present, which it isn't.

How do I go about fixing this?

### edit

I did also follow this:

``` bash
==> Caveats
libiconv is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libiconv first in your PATH run:
  echo 'export PATH="/usr/local/opt/libiconv/bin:$PATH"' >> ~/.zshrc

For compilers to find libiconv you may need to set:
  export LDFLAGS="-L/usr/local/opt/libiconv/lib"
  export CPPFLAGS="-I/usr/local/opt/libiconv/include"
````

**Comment by MeirShpilraien** [comment]
@rafie any idea?

**Comment by Rambatino** [comment]
So I fixed it with this: 

``` bash
 export DYLD_LIBRARY_PATH="/usr/lib:/usr/local/lib:/usr/local/opt"
```

Not sure if that helps you find a solution?

**Comment by Rambatino** [comment]
I'll close for now, it may help someone in the future (the key to making those symbols available was to pass the directory where the brew installed libiconv library is to DYLD_LIBRARY_PATH). For me DYLD_LIBRARY_PATH didn't exist, but if it does then maybe

``` bash
export DYLD_LIBRARY_PATH="/usr/lib:/usr/local/lib:/usr/local/opt:$DYLD_LIBRARY_PATH" 
```

Is a safer approach.
