### ISSUE TITLE
Changing bg.run to bg.register in KeyReader function crashes redis gears cluster

### ISSUE THREAD

**Issue by AlexMikhalev** [RedisGears/RedisGears#474]
Well, this one is complicated, I am not sure how to narrow it down any more:
* The function runs in the middle of the NLP pipeline: matching tokens against Aho Corasick pre build tree full code [here](https://github.com/applied-knowledge-systems/the-pattern-platform/blob/main/sentences_matcher_gears.py) 
Runs successfully. 
If I change 
```
bg = GearsBuilder('KeysReader')
bg.foreach(process_item)
bg.count()
bg.run('sentence:*',  mode="async_local",onRegistered=OnRegisteredAutomata)
```
to 
```
bg = GearsBuilder('KeysReader')
bg.foreach(process_item)
bg.count()
bg.register('sentence:*',  mode="async_local",onRegistered=OnRegisteredAutomata)
```
run changed to register, cluster becomes unstable and even when recover doesn't react on new records in sentence:* keyspace, although Gears function registeres successfully. I tried to pass keyTypes=['string','hash'] but it doesn't change behaviour. 
When I try to run previous - run gears function cluster fully crashes and never recovers.  
Bug report logs are in [gist](https://gist.github.com/AlexMikhalev/fa704d7b7d1ec54f65e8b1e0362a3f90) 
Steps to reproduce: 
```
git clone https://github.com/applied-knowledge-systems/the-pattern-platform.git 
cd conf && launch_cluster_docker.sh
```
in another terminal 
```
pip install gears-cli 
sh cluster_pipeline.sh
redis-cli -p 9001 -h 127.0.0.1 GRAPH.QUERY cord19medical "MATCH (n:entity) RETURN count(n) as entity_count"
```
It will run "run" version of gears. 
```
gears-cli run --host 127.0.0.1 --port 30001 sentences_matcher_register.py  --requirements requirements_gears_aho.txt
```
Observe crash. In not crashed `python RedisIntakeRedisClusterSample.py --nsamples 50` will add more samples - and registered function should start processing entities (entity count will change). 
Deployment uses official docker image for rgcluster with one addition - apt install build-essential as pyahocorasick have C component. RedigGraph is standard docker.

**Comment by MeirShpilraien** [comment]
@AlexMikhalev thanks for reporting, will check it out and update ASAP.

**Comment by MeirShpilraien** [comment]
@AlexMikhalev did you play with slot ranges? the only way I can see it happened is if you have key on shards which they do not belong to this shard ...

**Comment by MeirShpilraien** [comment]
OK, this is definitely considered a bug on RedisGears which should never crash the server (and we will fix it). But the reason the cluster becomes unstable is that you are doing the `loadAutomata` inside the OnRegister function which is called when the Redis lock is held. Although this `loadAutomata` takes a few seconds it's enough to cause the other nodes to think that the shard is not responsive which probably causes slots movement and the crash we saw. Please try to increase the time Redis will wait before deciding that the node is down, I believe this will solve the issue of cluster instability until we will solve the crash. You can do it by sending: `'CONFIG' 'set' 'cluster-node-timeout' '30000'` to all the shards (this will set the timeout to 30 seconds, the default is 5 seconds IIRC). You can also send it when you start the shards with `--cluster-node-timeout 30000`

**Comment by AlexMikhalev** [comment]
Thank you @MeirShpilraien, let me check it out. 
I already set `docker exec -it rgcluster /cluster/create-cluster call RG.CONFIGSET ExecutionMaxIdleTime 300000` as part of launch_cluster_docker.sh so adding one more settings should be easy.
And answering previous question - no, shards and slots are not touched other than via hashtag()
Am I right that the reason br.run works because it ignores onRegistered part?

**Comment by MeirShpilraien** [comment]
Yes, if you use run it is not calling the OnRegistered.

**Comment by AlexMikhalev** [comment]
Increasing timeout made it to work. Looking forward to proper bugfix.

**Comment by AlexMikhalev** [comment]
IMHO bg.register function now have a memory leak - rgcluster now consumes growing amount of memory, I left it running for a few hours and it eaten up to 60GB RAM with no new data added.

**Comment by MeirShpilraien** [comment]
@AlexMikhalev can you share the output of RG.PYSTATS to see if its the python that takes the memory or maybe its gears itself?

**Comment by AlexMikhalev** [comment]
@MeirShpilraien weekend project, apologies for delay.
Logs have 
==> 30009.log <==
89:S 19 Jan 2021 11:27:20.009 * Starting automatic rewriting of AOF on 36084795% growth
89:S 19 Jan 2021 11:27:20.018 * Background append only file rewriting started by pid 2979
89:S 19 Jan 2021 11:27:20.252 * AOF rewrite child asks to stop sending diffs.
2979:C 19 Jan 2021 11:27:20.252 * Parent agreed to stop sending diffs. Finalizing AOF...
2979:C 19 Jan 2021 11:27:20.252 * Concatenating 0.24 MB of AOF diff received from parent.
2979:C 19 Jan 2021 11:27:20.256 * SYNC append only file rewrite performed
2979:C 19 Jan 2021 11:27:20.266 * AOF rewrite: 50 MB of memory used by copy-on-write
89:S 19 Jan 2021 11:27:20.318 * Background AOF rewrite terminated with success
89:S 19 Jan 2021 11:27:20.318 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
89:S 19 Jan 2021 11:27:20.318 * Background AOF rewrite finished successfully

```
RG.PYSTATS 
1) "TotalAllocated"
2) (integer) 14619355277
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992088480
127.0.0.1:30001> RG.PYSTATS 
1) "TotalAllocated"
2) (integer) 15912965964
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992159846
127.0.0.1:30001> RG.PYSTATS 
1) "TotalAllocated"
2) (integer) 16223771030
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992160060
127.0.0.1:30001> RG.PYSTATS 
1) "TotalAllocated"
2) (integer) 17831689880
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992165929
127.0.0.1:30001> RG.PYSTATS 
1) "TotalAllocated"
2) (integer) 18172852133
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992166175
1) "TotalAllocated"
2) (integer) 20773723055
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992242496
```
Seems like Python memory allocation keeps growing.

**Comment by MeirShpilraien** [comment]
@AlexMikhalev does the python memory growth correlate with the memory growth as reported by Redis on ft.info?

**Comment by AlexMikhalev** [comment]
Do you mean RedisSearch FT INFO? https://oss.redislabs.com/redisearch/Commands/#ftinfo I don't have it installed. 
Pure rgcluster, no additional modules.
```
127.0.0.1:30001> MODULE LIST
1) 1) "name"
   2) "rg"
   3) "ver"
   4) (integer) 10002
```

**Comment by MeirShpilraien** [comment]
ohh sorry, wrote ft.info, I mean `info memory` command (pure Redis)

**Comment by AlexMikhalev** [comment]
Ok, latest (processing finished, nothing should be happening)
```
127.0.0.1:30001> RG.PYSTATS 
1) "TotalAllocated"
2) (integer) 29156684737
3) "PeakAllocated"
4) (integer) 1444591661
5) "CurrAllocated"
6) (integer) 992208739
```
```
127.0.0.1:30001> INFO MEMORY
# Memory
used_memory:1298561112
used_memory_human:1.21G
used_memory_rss:1364738048
used_memory_rss_human:1.27G
used_memory_peak:1450157472
used_memory_peak_human:1.35G
used_memory_peak_perc:89.55%
used_memory_overhead:7820990
used_memory_startup:6478336
used_memory_dataset:1290740122
used_memory_dataset_perc:99.90%
allocator_allocated:1299970400
allocator_active:1317629952
allocator_resident:1348112384
total_system_memory:67126087680
total_system_memory_human:62.52G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.01
allocator_frag_bytes:17659552
allocator_rss_ratio:1.02
allocator_rss_bytes:30482432
rss_overhead_ratio:1.01
rss_overhead_bytes:16625664
mem_fragmentation_ratio:1.05
mem_fragmentation_bytes:66217960
mem_not_counted_for_evict:3940
mem_replication_backlog:1048576
mem_clients_slaves:16986
mem_clients_normal:271776
mem_aof_buffer:3940
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
```
```
CLUSTER INFO
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:16
cluster_size:8
cluster_current_epoch:16
cluster_my_epoch:1
cluster_stats_messages_ping_sent:80943
cluster_stats_messages_pong_sent:80289
cluster_stats_messages_sent:161232
cluster_stats_messages_ping_received:80274
cluster_stats_messages_pong_received:80933
cluster_stats_messages_meet_received:15
cluster_stats_messages_received:161222
```

**Comment by MeirShpilraien** [comment]
But @AlexMikhalev I do not see the 60GB ram you are talking about, you probably restart the shards. If you can let it run again and monitor the `RG.PYSTATS` and `info memory` we will be able to see if it the python consuming the memory or something else. Currently, it looks like python is consuming most of the memory but I believe those are the AI models you load and should stay stable more or less (I believe).
Also please notice that we just release v1.0.5, I recommend to upgrade, there are some memory leak fixes there (especially on cluster management).

**Comment by AlexMikhalev** [comment]
@MeirShpilraien thank you. I will try update to re-run cluster inside docker tonight.
Do you have a recomended way to capture memory use for docker containers? Like prometheus or even command line script?

**Comment by AlexMikhalev** [comment]
Ok. I pulled new rgcluster docker and run processing on fresh cluster. Capturing 
docker exec -it rgcluster /cluster/create-cluster call INFO MEMORY >>
[memory_info_before_register.txt](https://github.com/RedisGears/RedisGears/files/5837801/memory_info_before_register.txt)
before registering function, after registering:
[memory_info_after_register.txt](https://github.com/RedisGears/RedisGears/files/5837803/memory_info_after_register.txt)
after registering waiting for 180 seconds with no additional data processed
[memory_info_after_register_sleep180.txt](https://github.com/RedisGears/RedisGears/files/5837807/memory_info_after_register_sleep180.txt)
And corresponding RG.PYSTATS
docker exec -it rgcluster /cluster/create-cluster call RG.PYSTATS >>
[rg_py_stats_before_register.txt](https://github.com/RedisGears/RedisGears/files/5837818/rg_py_stats_before_register.txt)
[rg_py_stats_after_register.txt](https://github.com/RedisGears/RedisGears/files/5837820/rg_py_stats_after_register.txt)
[rg_py_stats_after_register_sleep180.txt](https://github.com/RedisGears/RedisGears/files/5837821/rg_py_stats_after_register_sleep180.txt)

And after adding 25 more articles

[memory_info_after_register_sleep180_new_data25.txt](https://github.com/RedisGears/RedisGears/files/5837847/memory_info_after_register_sleep180_new_data25.txt)
[rg_py_stats_after_register_sleep180_new_data_25.txt](https://github.com/RedisGears/RedisGears/files/5837848/rg_py_stats_after_register_sleep180_new_data_25.txt)

**Comment by AlexMikhalev** [comment]
:point_up_2: That's actually confusing. Seems adding new data made RG.PYSTATS go down compared to just idle cluster for 3 minutes.

**Comment by AlexMikhalev** [comment]
Seems like cluster marginally increasing redis (core) memory usage and deallocating python memory, which seems like correct behaviour. 

Re-run above adding 25 more articles (75 total). 
[memory_info_after_register_sleep180_new_data25_1.txt](https://github.com/RedisGears/RedisGears/files/5837914/memory_info_after_register_sleep180_new_data25_1.txt)
[memory_info_after_register_sleep180_new_data75.txt](https://github.com/RedisGears/RedisGears/files/5837915/memory_info_after_register_sleep180_new_data75.txt)

[rg_py_stats_after_register_sleep180_new_data_25_1.txt](https://github.com/RedisGears/RedisGears/files/5837917/rg_py_stats_after_register_sleep180_new_data_25_1.txt)

[rg_py_stats_after_register_sleep180_new_data75.txt](https://github.com/RedisGears/RedisGears/files/5837916/rg_py_stats_after_register_sleep180_new_data75.txt)

**Comment by MeirShpilraien** [comment]
@AlexMikhalev I still do not see the 60G you were mentioned before. Did you reached it just by setup a cluster with your code (https://github.com/applied-knowledge-systems/the-pattern-platform/blob/main/sentences_matcher_gears.py) and keep it idle? If so I will try to reproduce it myself and analyze.

**Comment by AlexMikhalev** [comment]
Yes, this is a code as above - but I commented those two lines:
```
       execute('XADD', 'nodes_matched_{%s}' % shard_id, '*','node_id',f'{source_entity_id}','node_name',f'{source_canonical_name}')
                    execute('XADD', 'nodes_matched {%s}' % shard_id,'*','node_id',f'{destination_entity_id}','node_name',f'{destination_canonical_name}')
```
there is no consumer for this stream yet. 
Let me know if I can help you investigate.

**Comment by AlexMikhalev** [comment]
@MeirShpilraien I think this bug can be closed - with current version memory allocation is so smooth that I forgot I had gears pipeline running.

**Comment by MeirShpilraien** [comment]
Thanks @AlexMikhalev , please reopen if you see it again.

**Comment by AlexMikhalev** [comment]
Thank you for such responsiveness - it's amazing to see how such bugs get fixed.
