### ISSUE TITLE
Redis Gears cluster can't start if data dir is enabled and have data

### ISSUE THREAD

**Issue by AlexMikhalev** [RedisGears/RedisGears#558]
I successfully run RedisGears (and RedisAI) in cluster mode using [docker compose](https://github.com/applied-knowledge-systems/the-pattern/blob/c6eb04a8f1f32fe1d8adb61c0dac795877cdf175/docker-compose.prod.yml#L31) , [Dockerfile](https://github.com/applied-knowledge-systems/the-pattern-platform/blob/a38bd2f551439e05af1aac9fb551e3d3481fffde/conf/Dockerfile_redisai) for RedisGears+RedisAI and [docker-config](https://github.com/applied-knowledge-systems/the-pattern-platform/blob/a38bd2f551439e05af1aac9fb551e3d3481fffde/conf/docker-config_prod.sh). 

When I decided to restart, cluster crashes with "Node 127.0.0.1:30001 replied with error:
LOADING Redis is loading the dataset in memory"
Adding cluster node timeout - via TIMEOUT variable and cluster-node-timeout into config didn't solve issue:

```
cat the-pattern-platform/conf/docker-config_prod.sh 
BIN_PATH=/usr/local/bin
CLUSTER_HOST=127.0.0.1
CONTAINER_IP=`hostname -I`
PORT=30000
TIMEOUT=60000
#NODES=$(cat /proc/cpuinfo| grep cores | wc -l)
NODES=10
REPLICAS=1
PROTECTED_MODE=no
ADDITIONAL_OPTIONS="--dir /data --cluster-node-timeout 60000 --cluster-announce-ip $CONTAINER_IP --loadmodule /usr/lib/redis/modules/redisai.so --loadmodule /var/opt/redislabs/lib/modules/redisgears.so Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so PythonInstallationDir /var/opt/redislabs/modules/rg CreateVenv 1 DownloadDeps 1 "
```

Loading into an interactive mode for debugging:
```
docker run --entrypoint "/bin/bash" --name rgcluster -it -v $PWD/docker-config_prod.sh:/cluster/config.sh -v /home/alex/the-pattern/data/rgcluster_data:/data -p 30001:30001 -p 30002:30002 -p 30003:30003 --rm  rgcluster:latest
```

with @MeirShpilraien suggestion I could load data into shards separately:
```
redis-server --dbfilename dump-30001.rdb --loadmodule /usr/lib/redis/modules/redisai.so --loadmodule /var/opt/redislabs/lib/modules/redisgears.so Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so PythonInstallationDir /var/opt/redislabs/modules/rg CreateVenv 1 DownloadDeps 1

[W OperatorEntry.cpp:111] Warning: Registering a kernel (registered by RegisterOperators) for operator redis::execute for dispatch key (catch all) that overwrote a previously registered kernel with the same dispatch key for the same operator. (function registerKernel)
[W OperatorEntry.cpp:111] Warning: Registering a kernel (registered by RegisterOperators) for operator redis::asList for dispatch key (catch all) that overwrote a previously registered kernel with the same dispatch key for the same operator. (function registerKernel)
3130:M 10 May 2021 13:37:25.102 * <ai> TORCH backend loaded from /usr/lib/redis/modules/backends/redisai_torch/redisai_torch.so
3130:M 10 May 2021 13:37:32.659 * DB loaded from disk: 16.356 seconds
3130:M 10 May 2021 13:37:32.659 * Ready to accept connections
3130:M 10 May 2021 13:38:31.512 * 10000 changes in 60 seconds. Saving...
3130:M 10 May 2021 13:38:31.627 * Background saving started by pid 3247
```

but calling `./create-cluster start` produced [crash](https://gist.github.com/AlexMikhalev/31acacf1d08fcd6a59aa25e0b6a7831c)

I hope it will help.

**Comment by MeirShpilraien** [comment]
Thanks @AlexMikhalev 

The issue is that we try to read the stream before the cluster is initialized and the cluster returns and error, unfortunately, there is an assertion that there is not errors. two things we need to fix:
1. We can not assert that there is no error
2. We need to wait for cluster to initialized
