### ISSUE TITLE
RG.PYEXECUTE registrationId when creating KeysReader

### ISSUE THREAD

**Issue by XhrCkYsSgZokJL** [RedisGears/RedisGears#570]
When registering a KeysRreader gear through RG.PYEXECUTE, no registrationId is returned. 
Is there a relation between registering a KeysReader/StreamReader and receiving their respective registrationId directly?

**Comment by MeirShpilraien** [comment]
@XhrCkYsSgZokJL theoretically a single script (RG.PYEXECUTE) can register multiple Readers so return one ID does not make sense. You can put a description to your registrations and then search for it with RG.DUMPREGISTRATIONS and find the RegistrationID.

**Comment by XhrCkYsSgZokJL** [comment]
@MeirShpilraien That worked!  Closing now - thank you.
