### ISSUE TITLE
Building on OSX 11.4 using homebrew fails

### ISSUE THREAD

**Issue by chrisAtRedisLabs** [RedisGears/RedisGears#577]
"sudo make setup" fails after cloning including the dependencies fails as running homebrew as root is no longer supported: 

"
sudo make setup
Password:
Setting up system...
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

In ./deps/readies/bin/getpy2:
161      if is_command brew; then
162      	# the following is for avoiding python to be upgraded by brew silently,
163      	# hence disrupting pip installaitons
164  >>> 	runn brew upgrade python
165      fi
166      
167      check_variants

make: *** [Makefile:283: setup] Error 1
"

**Comment by chrisAtRedisLabs** [comment]
Please let me know if you need more details.

**Comment by MeirShpilraien** [comment]
@rafie @chayim ^^

**Comment by chayim** [comment]
@chrisAtRedisLabs If you run _make setup_ without sudo (assumes you have gnu make already brewed and in path) you should be fine.  Can you validate?  I can change the docs accordingly, but I just validated locally.

**Comment by chrisAtRedisLabs** [comment]
Still tries to symlink in /usr/local/bin

https://github.com/RedisLabsModules/readies/pull/51 should fix this.
