### ISSUE TITLE
periodically run batch jobs

### ISSUE THREAD

**Issue by szho42** [RedisGears/RedisGears#643]
Just wondering whether the current version supports to run a batch job periodically, with a given time interval. 
For example, to aggregate data every 30 mins?

Thanks

**Comment by MeirShpilraien** [comment]
No but you can see here a nice workaround: https://forum.redis.com/t/redis-gears-cron-scheduler/972/2

**Comment by szho42** [comment]
oh, yeah, that is defintely a good workaround.
Thanks
