### ISSUE TITLE
any plan to support TimeSeriesReader in event mode

### ISSUE THREAD

**Issue by szho42** [RedisGears/RedisGears#644]
Just wondering whether there are any workarounds for registering redisgears to response to redistimeseries updates?

**Comment by MeirShpilraien** [comment]
From what I know RedisTS supports keys space notifications sense v1.6 (@danni-m correct me if I am wrong), so the KeysReader provided by RedisGears should work with it. Please notice that RedisGears will not give you the data, you can read the data by invoking RedisTS commands on the key.

**Comment by szho42** [comment]
thanks for the information. In our case, we would like to perform simple streaming process, which takes inputs from redisTS and write to other destinations.
I am not sure whether key space notifications can capture time series updates in RedisTS?

**Comment by MeirShpilraien** [comment]
Sorry for the late response, it will be possible with 1.2 version (which will be GA soon). But only with Redis 6.2 and above and only if TS fire keys space events (I believe @danni-m can answer that).

**Comment by MeirShpilraien** [comment]
@szho42 closing, please reopen if any further help is needed.
