### ISSUE TITLE
redisgears.so error in ubuntu 18.04

### ISSUE THREAD

**Issue by baozitao** [RedisGears/RedisGears#646]
system ： ubuntu 18.04
redis:6.0.2
1.I compiled it according to the steps of the webpage（https://oss.redis.com/redisgears/quickstart.html）, without any error, the compilation was completed, when I loaded the redisgears module,load success，redis-cli executed 
RG.PYEXECUTE "GearsBuilder().run()", 
Terminal error： ( error) ERR unknown command `RG.PYEXECUTE`, with args beginning with: `GearsBuilder().run()`,error,
2.The size of my compiled redisgears.so is 1.2MB
3.I downloaded the compiled redisgears.so module for ubuntu 18.04 from the official website, the size is 4.4MB, and it works normally.

There is no error when compiling, I don’t know where something went wrong and the size of redisgears.so is very different.,Is there anything else I need to pay attention to when compiling?

**Comment by MeirShpilraien** [comment]
Hey @baozitao you probably compiled the master branch, Notice that the python is now plugin that need to be loaded using --plugin argument. Look here for more information: https://github.com/RedisGears/RedisGears/pull/560/files

**Comment by baozitao** [comment]
Great, successful, it is indeed lack of python library, thank you very much!! @MeirShpilraien
