### ISSUE TITLE
Plugin timeseries does not exists and required to load rdb

### ISSUE THREAD

**Issue by mikhailredis** [RedisGears/RedisGears#648]
I just updated to the latest versions of RedisGears and RedisTimeSeries and can't load my rdb file with the error `<rg> Plugin timeseries does not exists and required to load rdb`

```
1:M 16 Dec 2021 03:04:19.862 * <rg> Found python installation under: /var/opt/redislabs/modules/rg//python3_99.99.99/
1:M 16 Dec 2021 03:04:19.968 * Module 'rg' loaded from /var/opt/redislabs/lib/modules/redisgears.so
1:M 16 Dec 2021 03:04:19.968 * Loading RDB produced by version 6.2.5
1:M 16 Dec 2021 03:04:19.968 * RDB age 1573 seconds
1:M 16 Dec 2021 03:04:19.968 * RDB memory usage when created 637.57 Mb
1:M 16 Dec 2021 03:04:19.968 # <rg> Plugin timeseries does not exists and required to load rdb
1:M 16 Dec 2021 03:04:19.968 # The RDB file contains module AUX data for the module type 'GEARS_DT0', that the responsible module is not able to load. Check for modules log above for additional clues.
```

as I can see RTS loaded successfully before:
```
1:M 16 Dec 2021 03:04:19.842 * <timeseries> RedisTimeSeries version 999999, git_sha=e509dc456ca6a08010a194f0767bb58fea5dabbb
1:M 16 Dec 2021 03:04:19.843 * <timeseries> Redis version found by RedisTimeSeries : 6.2.5 - oss
1:M 16 Dec 2021 03:04:19.843 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
1:M 16 Dec 2021 03:04:19.843 * <timeseries> loaded server DUPLICATE_POLICY: block
1:M 16 Dec 2021 03:04:19.843 * <timeseries> Setting default series ENCODING to: compressed
1:M 16 Dec 2021 03:04:19.843 * <timeseries> Detected redis oss
1:M 16 Dec 2021 03:04:19.843 * Module 'timeseries' loaded from /usr/lib/redis/modules/redistimeseries.so
```

Did anything change recently related to RTS?

**Comment by MeirShpilraien** [comment]
You probably used the master version of both RedisTS and RedisGears. RedisTS wrongly used the C api of RedisGears and this is why you see this error. It was fixes on the currently master (RedisTS is no longer use RedisGears, instead it uses [libmr](https://github.com/RedisGears/LibMR)). Let me know if you need the data on this RDB and I can try help you recover it.

**Comment by mikhailredis** [comment]
@MeirShpilraien, you are correct my images built on top of the edge version and it explains it.
I was able to fallbacks the previous image and running the older version now on our demo server.
Is it safe to update now or RDB still won't load?

**Comment by MeirShpilraien** [comment]
No it will still not work, what I can do is to give you a temporary branch for you to use that will load the RDB and save it in such way that it will be loadable on the current master version. Sounds good?

**Comment by MeirShpilraien** [comment]
So you will need to update to this temporary branch, save the RDB and then upgrade to current master.

**Comment by MeirShpilraien** [comment]
Will prepare it and update ASAP

**Comment by MeirShpilraien** [comment]
@mikhailredis please try to use this branch https://github.com/RedisGears/RedisGears/tree/temp_fix_for_mikhailredis. It should allow you to load the "corrupted" RDB with the latest TS. After you successes you can return to the any RedisGears branch you want.

**Comment by MeirShpilraien** [comment]
@mikhailredis any updates?

**Comment by mikhailredis** [comment]
@MeirShpilraien Thank you, it worked flawlessly.
