### ISSUE TITLE
Redis OOM when running PythonReader with not a generator function

### ISSUE THREAD

**Issue by mikhailredis** [RedisGears/RedisGears#649]
When running PythonReader with lambda function which is not generator does hung and goes OOM:
```
RG.PYEXECUTE "gb = GB('PythonReader').run(lambda x: execute('XLEN', 'edges_matched_{' + hashtag() + '}'), collect=False)"
```

I understand that it should be a generator function and it's more a user error, but Redis should not go OOM and crash the server.

**Comment by MeirShpilraien** [comment]
@mikhailredis I tried to run you example and I an getting this:
```
127.0.0.1:6379> RG.PYEXECUTE "gb = GB('PythonReader').run(lambda x: execute('XLEN', 'edges_matched_{' + hashtag() + '}'), collect=False)"
1) (empty array)
2) 1) "Error type: <class 'TypeError'>, Value: <lambda>() missing 1 required positional argument: 'x'"
```
I do not get any OOM error, anything I am doing wrong?

**Comment by mikhailredis** [comment]
@MeirShpilraien It it works, it may be fixed already.
Thank you for looking into it.
