### ISSUE TITLE
Build Fails on Devuan(Debian) Linux

### ISSUE THREAD

**Issue by irthomasthomas** [RedisGears/RedisGears#666]
Hi, I am using Devuan which is Debian without systemD. I have built redis server and a bunch of modules OK, but the gears build fails during make all:
Desk% make all
Compiling /home/tommy/Development/redis/RedisGears/plugins/python/redisgears_python.c...
Compiling /home/tommy/Development/redis/RedisGears/plugins/python/globals.c...
Compiling /home/tommy/Development/redis/RedisGears/src/utils/dict.c...
Compiling /home/tommy/Development/redis/RedisGears/src/utils/thpool.c...
Compiling /home/tommy/Development/redis/RedisGears/src/utils/buffer.c...
Linking ../../bin/linux-x64-release/gears_python/gears_python.so...
Compiling src/cluster.c...
<command-line>: warning: missing terminating " character
/usr/bin/ld: cannot find ceres-x64": No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:223: bin/linux-x64-release/src/cluster.o] Error 1

I had to tweak a couple of lines in setup.py and platform.py so that it would treat Devuan as Debian to get it this far.

**Comment by MeirShpilraien** [comment]
@chayim any suggestion here?

**Comment by irthomasthomas** [comment]
I think I was using main branch there, but I just did a clean test on 1.0.9 and it does similar. 

Compiling src/utils/adlist.c...
<command-line>: warning: missing terminating " character
gcc: warning: ceres-x64": linker input file unused because linking not done
gcc: error: ceres-x64": linker input file not found: No such file or directory
make: *** [Makefile:231: bin/linux-x64-release/src/utils/adlist.o] Error 1

**Comment by irthomasthomas** [comment]
Hi I have tried this on a few different VMs now, and I still can't get it to build. Debian 10 and 11 get the furthest along, but they both fail on building libevent...
configure: error: cannot find install-sh, install.sh, or shtool in "/home/tommy/RedisGears/deps/libevent" "/home/tommy/RedisGears/deps/libevent/.." "/home/tommy/RedisGears/deps/libevent/../.."
make[1]: *** [../../deps/readies/mk/configure.rules:5: ../../bin/linux-x64-release/libevent/Makefile] Error 1
make: *** [Makefile:330: bin/linux-x64-release/libevent/.libs/libevent.a] Error 2

Any suggestions?
