### ISSUE TITLE
BUILD FAILURE Redis gears java runtime plugin 

### ISSUE THREAD

**Issue by vsharathis** [RedisGears/RedisGears#716]
Hi Jvmplugin error 

Operating system : Centos7

Building jvmplugin...
make -C plugins/jvmplugin PYTHONDIR=/root/sharath/tag/v1.0.9/bin/linux-x64-release/python3_99.99.99
OS=linux
make -C ./src/
make[2]: Nothing to be done for 'all'.
cd gears_runtime; mvn -q package
[debug] execute contextualize
[ERROR] COMPILATION ERROR :
[ERROR] /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java:[18,26] cannot find symbol
  symbol:   class HotSpotDiagnosticMXBean
  location: package com.sun.management
[ERROR] /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java:[718,13] cannot find symbol
  symbol:   class HotSpotDiagnosticMXBean
  location: class gears.GearsBuilder<T>
[ERROR] /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java:[719,68] cannot find symbol
  symbol:   class HotSpotDiagnosticMXBean
  location: class gears.GearsBuilder<T>
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project gear_runtime: Compilation failure: Compilation failure:
[ERROR] /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java:[18,26] cannot find symbol
[ERROR] symbol:   class HotSpotDiagnosticMXBean
[ERROR] location: package com.sun.management
[ERROR] /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java:[718,13] cannot find symbol
[ERROR] symbol:   class HotSpotDiagnosticMXBean
[ERROR] location: class gears.GearsBuilder<T>
[ERROR] /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java:[719,68] cannot find symbol
[ERROR] symbol:   class HotSpotDiagnosticMXBean
[ERROR] location: class gears.GearsBuilder<T>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make[1]: *** [Makefile:40: GearsRuntime] Error 1
make: *** [Makefile:361: jvmplugin] Error 2
-bash-4.2# vi /root/sharath/tag/v1.0.9/plugins/jvmplugin/gears_runtime/src/main/java/gears/GearsBuilder.java
-bash-4.2# mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.079s
[INFO] Finished at: Fri Feb 04 11:57:12 UTC 2022
[INFO] Final Memory: 5M/9M

**Comment by MeirShpilraien** [comment]
Hey @vsharathis can you please specify the java version you are using?

**Comment by vsharathis** [comment]
Hi @MeirShpilraien , Sure
**-bash-4.2# java -version**
openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14+9-LTS, mixed mode, sharing)
-bash-4.2#
**-bash-4.2# mvn --version**
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_311, vendor: IBM Corporation
Java home: /usr/lib/jvm/java-1.8.0-ibm-1.8.0.7.0-1jpp.1.el7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.36.2.el7.x86_64", arch: "amd64", family: "unix"
-bash-4.2#

**Comment by vsharathis** [comment]
hi @MeirShpilraien , i found an issue, its not a problem with the build, it's a problem with maven, maven referring to the old java home. sorry for the confusion,
