### ISSUE TITLE
Pause/unpause gear function

### ISSUE THREAD

**Issue by spicy-sauce** [RedisGears/RedisGears#724]
Would be nice to support this instead of unregistering (to simulate stop operation) the gear function (with abort pending or without it) and reregistering it (to simulate start operation)

**Comment by MeirShpilraien** [comment]
@spicy-sauce I can see how it is useful on streams (you will not lose events because the data is on the stream) but on KeysReader, what is the expected behaviour? Should you lose events or you expect the events to be accumulated and trigger once the registration is unpause?

**Comment by spicy-sauce** [comment]
@MeirShpilraien I think that as long both pause and unregister commands are supported, we cover all the options, as long as the documentation stresses this out properly. Although I can see why one might find the pause command not needed for KeysReader. I think our rule thumb can be that unpause command continues from the last place before the pause command, that means that all the events will be accumulated so once you're unpausing it, they'll be processed. If someone is not interested with this behavior, he or she can just unregister the gear function.  We can also add another argument to define the behavior in this case, but I don't think it's needed.
WDYT?

**Comment by MeirShpilraien** [comment]
@spicy-sauce If we will accumulate all the events that happened during the pause, we will give a false feeling that you will not lose events, even on pause, this is of course not the case if the shard crashes for example (on streams you will not lose events, they are saved on the stream. With key space notification you will lose them ...). I tend to simply do the simple solution and not accumulate the events. If it is important not to lose key space events on pause then the user can write all the events into a stream and use a `StreamReader` to consume the stream, the user can then pause **only** the stream registration and not the keys space notification registration.

**Comment by spicy-sauce** [comment]
@MeirShpilraien I see your point - as it's more relevant to `StreamsReader`, we can definitely not implement this in `KeysReader` to avoid not intuitive behavior. This of course should be well documented. Thanks!
