### ISSUE TITLE
RG.DUMPREGISTRATIONS - -nan in avgRunDurationMS and avgEstimatedLagMS

### ISSUE THREAD

**Issue by spicy-sauce** [RedisGears/RedisGears#731]
15) "avgRunDurationMS"
       16) "-nan"
       17) "lastEstimatedLagMS"
       18) (integer) 0
       19) "avgEstimatedLagMS"
       20) "-nan"

**Comment by MeirShpilraien** [comment]
Thanks @spicy-sauce , those stats appears as `-nan` is no data was processed yet. We will change it to 0.
