### ISSUE TITLE
RG.REFRESHCLUSTER command exits redis-server process

### ISSUE THREAD

**Issue by varun-vymo** [RedisGears/RedisGears#817]
`127.0.0.1:6379> RG.REFRESHCLUSTER
Error: Server closed the connection
(0.59s)`

`=== REDIS BUG REPORT START: Cut & paste starting from here ===
4361:M 24 Aug 2022 10:13:29.496 # === ASSERTION FAILED ===
4361:M 24 Aug 2022 10:13:29.496 # ==> src/cluster.c:719 'RedisModule_CallReplyLength(nodeDetailsRelpy) == 3' is not true

------ STACK TRACE ------

Backtrace:
/var/opt/redislabs/modules/rg/10205/redisgears.so(+0x7e3c8)[0x7f15445df3c8]
/var/opt/redislabs/modules/rg/10205/redisgears.so(+0xb92a0)[0x7f154461a2a0]
/var/opt/redislabs/modules/rg/10205/redisgears.so(+0xb95a4)[0x7f154461a5a4]
/var/opt/redislabs/modules/rg/10205/redisgears.so(+0xb9b55)[0x7f154461ab55]
/var/opt/redislabs/modules/rg/10205/redisgears.so(event_base_loop+0x2da)[0x7f154461b2d8]
/var/opt/redislabs/modules/rg/10205/redisgears.so(+0x7c585)[0x7f15445dd585]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f1545a956ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f15457cb51d]

------ INFO OUTPUT ------
# Server
redis_version:7.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:161e4fdc7139f09c
redis_mode:cluster
os:Linux 4.15.0-1113-azure x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:5.4.0
process_id:4361
process_supervised:no
run_id:d7613ad66ac152ea0134cf00972b6e4687699919
tcp_port:6379
server_time_usec:1661316209496205
uptime_in_seconds:20
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:371825
executable:/usr/local/bin/redis-server
config_file:/etc/redis/6379.conf
io_threads_active:0

# Clients
connected_clients:1
cluster_connections:4
maxclients:10000
client_recent_max_input_buffer:20480
client_recent_max_output_buffer:20504
blocked_clients:1
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:10509248
used_memory_human:10.02M
used_memory_rss:59265024
used_memory_rss_human:56.52M
used_memory_peak:10509248
used_memory_peak_human:10.02M
used_memory_peak_perc:100.03%
used_memory_overhead:10075157
used_memory_startup:10027720
used_memory_dataset:434091
used_memory_dataset_perc:90.15%
allocator_allocated:11069976
allocator_active:11689984
allocator_resident:17084416
total_system_memory:8364716032
total_system_memory_human:7.79G
used_memory_lua:31744
used_memory_vm_eval:31744
used_memory_lua_human:31.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:32768
used_memory_vm_total:64512
used_memory_vm_total_human:63.00K
used_memory_functions:184
used_memory_scripts:184
used_memory_scripts_human:184B
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.06
allocator_frag_bytes:620008
allocator_rss_ratio:1.46
allocator_rss_bytes:5394432
rss_overhead_ratio:3.47
rss_overhead_bytes:42180608
mem_fragmentation_ratio:5.75
mem_fragmentation_bytes:48966368
mem_not_counted_for_evict:8
mem_replication_backlog:20508
mem_total_replication_buffers:20504
mem_clients_slaves:0
mem_clients_normal:22297
mem_cluster_links:4352
mem_aof_buffer:8
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:1
rdb_bgsave_in_progress:0
rdb_last_save_time:1661316189
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:925696
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:9
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:29649718
aof_base_size:32036
aof_pending_rewrite:0
aof_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:3
total_commands_processed:48
instantaneous_ops_per_sec:2
total_net_input_bytes:1604
total_net_output_bytes:174513
total_net_repl_input_bytes:0
total_net_repl_output_bytes:902
instantaneous_input_kbps:0.08
instantaneous_output_kbps:0.00
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:2
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:1525
total_forks:1
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:45
total_writes_processed:14
io_threaded_reads_processed:0
io_threaded_writes_processed:0
reply_buffer_shrinks:3
reply_buffer_expands:0

# Replication
role:master
connected_slaves:2
slave0:ip=127.0.0.1,port=7379,state=online,offset=28,lag=0
slave1:ip=127.0.0.1,port=8379,state=online,offset=28,lag=0
master_failover_state:no-failover
master_replid:904950786fdab6e11bffa9312e5edf0955a7a1a0
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:28
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:28

# CPU
used_cpu_sys:0.082089
used_cpu_user:0.306756
used_cpu_sys_children:0.003918
used_cpu_user_children:0.006812
used_cpu_sys_main_thread:0.000000
used_cpu_user_main_thread:0.000999

# Modules
module:name=rg,ver=10205,api=1,filters=1,usedby=[rg],using=[rg],options=[]

# Commandstats
cmdstat_psync:calls=2,usec=170,usec_per_call=85.00,rejected_calls=0,failed_calls=0
cmdstat_replconf:calls=36,usec=239,usec_per_call=6.64,rejected_calls=0,failed_calls=0
cmdstat_command|docs:calls=1,usec=1196,usec_per_call=1196.00,rejected_calls=0,failed_calls=0
cmdstat_config|get:calls=3,usec=27,usec_per_call=9.00,rejected_calls=0,failed_calls=0
cmdstat_rg.infocluster:calls=1,usec=6,usec_per_call=6.00,rejected_calls=0,failed_calls=0
cmdstat_cluster|slots:calls=1,usec=55,usec_per_call=55.00,rejected_calls=0,failed_calls=0
cmdstat_rg.refreshcluster:calls=1,usec=35,usec_per_call=35.00,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=2,usec=11,usec_per_call=5.50,rejected_calls=0,failed_calls=0
cmdstat_info:calls=1,usec=23,usec_per_call=23.00,rejected_calls=0,failed_calls=0

# Errorstats

# Latencystats
latency_percentiles_usec_psync:p50=73.215,p99=97.279,p99.9=97.279
latency_percentiles_usec_replconf:p50=2.007,p99=169.983,p99.9=169.983
latency_percentiles_usec_command|docs:p50=1196.031,p99=1196.031,p99.9=1196.031
latency_percentiles_usec_config|get:p50=10.047,p99=11.007,p99.9=11.007
latency_percentiles_usec_rg.infocluster:p50=6.015,p99=6.015,p99.9=6.015
latency_percentiles_usec_cluster|slots:p50=55.039,p99=55.039,p99.9=55.039
latency_percentiles_usec_ping:p50=3.007,p99=8.031,p99.9=8.031
latency_percentiles_usec_info:p50=23.039,p99=23.039,p99.9=23.039

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=19 addr=127.0.0.1:45898 laddr=127.0.0.1:6379 fd=28 name= age=20 idle=0 flags=S db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=1 omem=20504 tot-mem=42776 events=r cmd=replconf user=default redir=-1 resp=2
id=20 addr=127.0.0.1:45900 laddr=127.0.0.1:6379 fd=29 name= age=20 idle=0 flags=S db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=1 omem=20504 tot-mem=42776 events=r cmd=replconf user=default redir=-1 resp=2
id=21 addr=172.18.1.4:58740 laddr=172.18.3.17:6379 fd=30 name= age=4 idle=0 flags=b db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=17 multi-mem=0 rbs=1024 rbp=22 obl=0 oll=0 omem=0 tot-mem=22297 events=r cmd=rg.refreshcluster user=default redir=-1 resp=2

------ MODULES INFO OUTPUT ------
# rg
rg_nexecutions:0
rg_nregistrations:0

# rg_regisrations

# rg_plugins
rg_GearsPythonPlugin:version=10000
rg_GearsJVMPlugin:version=999999

# rg_python_stats
rg_TotalAllocated:24302216
rg_PeakAllocated:8311472
rg_CurrAllocated:8274544

# rg_python_requirements

# rg_python_sessions

# rg_jvm_sessions

# rg_jvm_stats
rg_jvm_mem_stats:["runtimeReport",["heapTotalMemory",132120576,"heapFreeMemory",129727400,"heapMaxMemory",2092957696],"memoryMXBeanReport",["heapMemory",{"init":132120576,"used":2097152,"committed":132120576,"max":2092957696},"nonHeapMemory",{"init":7667712,"used":8521576,"committed":15269888,"max":-1}],"pools",["CodeHeap 'non-nmethods'",{"init":2555904,"used":1062784,"committed":2555904,"max":5832704},"Metaspace",{"init":0,"used":7068280,"committed":7602176,"max":-1},"CodeHeap 'profiled nmethods'",{"init":2555904,"used":468480,"committed":2555904,"max":122912768},"Compressed Class Space",{"init":0,"used":664944,"committed":786432,"max":1073741824},"G1 Eden Space",{"init":15728640,"used":3145728,"committed":15728640,"max":-1},"G1 Old Gen",{"init":116391936,"used":0,"committed":116391936,"max":2092957696},"G1 Survivor Space",{"init":0,"used":0,"committed":0,"max":-1},"CodeHeap 'non-profiled nmethods'",{"init":2555904,"used":90368,"committed":2555904,"max":122912768}],"totalAllocatedMemory",288163664,"totalAllocatedMemoryHuman","274.8142852783203mb"]

------ CONFIG DEBUG OUTPUT ------
slave-read-only yes
lazyfree-lazy-eviction no
io-threads-do-reads no
lazyfree-lazy-user-del no
io-threads 1
lazyfree-lazy-expire no
repl-diskless-sync yes
replica-read-only yes
proto-max-bulk-len 512mb
lazyfree-lazy-server-del no
sanitize-dump-payload no
list-compress-depth 0
client-query-buffer-limit 1gb
lazyfree-lazy-user-flush no
repl-diskless-load disabled
activedefrag no

------ FAST MEMORY TEST ------
4361:M 24 Aug 2022 10:13:29.854 # main thread terminated
4361:M 24 Aug 2022 10:13:29.854 # Bio thread for job type #0 terminated
4361:M 24 Aug 2022 10:13:29.854 # Bio thread for job type #1 terminated
4361:M 24 Aug 2022 10:13:29.854 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== REDIS BUG REPORT END. Make sure to include from START to END. ===`

**Comment by MeirShpilraien** [comment]
Fixed on: https://github.com/RedisGears/RedisGears/pull/818
