### ISSUE TITLE
Execution max idle reached

### ISSUE THREAD

**Issue by NirmalP29** [RedisGears/RedisGears#822]
```
RG.REFRESHCLUSTER
OK
RG.PYEXECUTE "GB().run()"
1) (empty array)
2) 1) "Execution max idle reached"
(10.00s)
```

I am using this version
```
 module list
1) 1) "name"
   2) "rg"
   3) "ver"
   4) (integer) 10206
   5) "path"
   6) "/app/RedisGears/bin/linux-x64-release/redisgears.so"
   7) "args"
   8) 1) "Plugin"
      2) "/app/RedisGears/bin/linux-x64-release/gears_python/gears_python.so"
```

Can someone please help me solve this error?

**Comment by thomascaudron** [comment]
Hi @NirmalP29,

This is based on the 'ExecutionMaxIdleTime' setting: https://oss.redis.com/redisgears/configuration.html#executionmaxidletime

One of the external calls within the script was probably blocked or taking to long to respond.
From the docs:

>  The main reason for idle time is an execution that's blocked on waiting for records from another shard that had failed (i.e., crashed). In that case, the execution will be aborted after the specified time limit.

**Comment by NirmalP29** [comment]
Thanks @thomascaudron, It was tls issue. Tls was enabled in redis but not in redis gears.

**Comment by MeirShpilraien** [comment]
@NirmalP29 can we close the issue?
