### ISSUE TITLE
Necessary to pass accessed keys as arguments?

### ISSUE THREAD

**Issue by 4ext** [RedisGears/RedisGears#877]
Hello,

could someone please tell me if it's also necessary to pass any keys accessed by RG functions as arguments (CommandReader/FCALL), as it's the case with Redis functions or lua scripts (or at least it should be).
(I'm trying to avoid passing too many "key" arguments with each call to a function)

Thank you very much!

**Comment by MeirShpilraien** [comment]
Hey @4ext 

There is no obligation to do that but on cluster, but if you try to access keys that are not located on the current shard you will get an error. What you can do is to pass one key as an indicator (tells on which shard the function should be execution), and your function code should make sure to only access keys which located on the same hashslot.

On RedisGears you can also read data from other shards either using, not sure if you are using Gears 1 with python on Gears 2 with JS. You can take a look here: https://github.com/RedisGears/RedisGears/blob/master/docs/cluster_support.md

**Comment by 4ext** [comment]
Thank you very much @MeirShpilraien , passing just one key identifying the shard is a great solution.
Also thanks for pointing to the doc about remote functions, that's very useful.
